timeout: 3600s
steps:
- name: 'ubuntu'
  args:
  - 'bash'
  - '-c'
  - |
    mkdir config/${_BACK_UP_PROJECT}
    cp ../config/${_BACK_UP_PROJECT}/data_catalog.json config/${_BACK_UP_PROJECT}/data_catalog.json

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud beta pubsub topics create ${_TOPIC_NAME}
    python3 scripts/create_backup_topic_iam.py ${_BACK_UP_PROJECT} | tee backuptopiciam.json
    gcloud beta pubsub topics set-iam-policy projects/${PROJECT_ID}/topics/${_TOPIC_NAME} backuptopiciam.json -q

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud builds submit --project=${_BACK_UP_PROJECT} --substitutions=$(../config/backup.config.sh),_PROJECT_SOURCE=${PROJECT_ID} .
  dir: 'functions/backup-build'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - '${PROJECT_ID}-git-backup-func'
  - '--entry-point=receive_pubsub_backup_trigger_func'
  - '--runtime=python37'
  - '--trigger-topic=${_TOPIC_NAME}'
  - '--region=${_DEPLOYMENT_REGION}'
  - '--set-env-vars=PROJECT_ID=${PROJECT_ID},BACKUP_PROJECT_ID=${_BACK_UP_PROJECT}'
  - '--timeout=300'
