timeout: 1200s
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'services'
    - 'enable'
    - 'cloudbuild.googleapis.com'
    - 'deploymentmanager.googleapis.com'
    - 'cloudfunctions.googleapis.com'
    - 'cloudresourcemanager.googleapis.com'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    for pr in $(python3 scripts/listprojects.py config/projects.json)
    do
      gsutil mb -c regional -l europe-west1 gs://${PROJECT_ID}-${pr}-backup-stg/
      gsutil iam ch serviceAccount:${pr}@appspot.gserviceaccount.com:roles/storage.legacyBucketWriter gs://${PROJECT_ID}-${pr}-backup-stg/
    done

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cp ../config.py config.py
    cp ../requirements.txt requirements.txt
    for pr in $(python3 ../scripts/listprojects.py ../config/projects.json)
    do
      gcloud builds submit --substitutions=_BUCKET_NAME="${PROJECT_ID}-${pr}-backup-stg",_PROJECT_NAME=${pr} .
    done
  dir: 'test_git_backup'


