steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - '${_PROJECT_NAME}-backup-test-func'
  - '--entry-point=git_data_cloud_backup_testing_func'
  - '--runtime=python37'
  - '--trigger-resource=${_BUCKET_NAME}'
  - '--trigger-event=google.storage.object.finalize'
  - '--set-env-vars=PROJECT_ID=${PROJECT_ID},BACKUP_PROJECT_ID=${PROJECT_ID}'
  - '--region=europe-west1'